commands: ['go ahead',
           'back',
           'left',
           'right',
           'stop',
           'look left',
           'look right',
           'happy',
           'angry',
           'sad',
           'neutral',
           'confused']
